// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"fmt"

	"github.com/eullerpereira94/sqlc_enum_test/types"
)

type Colors string

const (
	ColorsRed   Colors = "red"
	ColorsBlue  Colors = "blue"
	ColorsGreen Colors = "green"
)

func (e *Colors) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Colors(s)
	case string:
		*e = Colors(s)
	default:
		return fmt.Errorf("unsupported scan type for Colors: %T", src)
	}
	return nil
}

type Box struct {
	ID    int64
	Name  string
	Color types.NullColors
}
